### ISSUE TITLE
pls add Xcode 7

### ISSUE THREAD

**Issue by leewi9** [zafarella/OSX-RAMDisk#36]
pls add Xcode 7 thanks

**Comment by zafarella** [comment]
can be added as separate ramdisk with mount point at `~/Library/Developer/Xcode/DerivedData` which is common known. @leewi9  can you please confirm this is what can help. I am not daily ios programmer - limited knowledge. Thanks.

**Comment by leewi9** [comment]
@zafarella tested, confirmed, thanks.

the worked code like this:

```
# Move Cache to Ramdisk.
DISK=`/usr/bin/hdiutil attach -nobrowse -nomount ram://1048576`  # 512MB
/usr/sbin/diskutil erasevolume HFS+ "RamDiskCache" $DISK
CACHEDIR="/Volumes/RamDiskCache"

# Safari Cache
/bin/rm -rvf ~/Library/Caches/com.apple.Safari
/bin/mkdir -pv $CACHEDIR/Apple/Safari
/bin/ln -v -s $CACHEDIR/Apple/Safari /Users/leewi9/Library/Caches/com.apple.Safari

# iTunes Cache
/bin/rm -rvf ~/Library/Caches/com.apple.iTunes
/bin/mkdir -pv $CACHEDIR/Apple/iTunes
/bin/ln -v -s $CACHEDIR/Apple/iTunes /Users/leewi9/Library/Caches/com.apple.iTunes

＃ Xcode Cache
/bin/rm -rvf ~/Library/Developer/Xcode/DerivedData
/bin/mkdir -pv $CACHEDIR/Apple/Xcode
/bin/ln -v -s $CACHEDIR/Apple/Xcode /Users/leewi9/Library/Developer/Xcode/DerivedData
```

**Comment by zafarella** [comment]
thanks @leewi9 , will incorporate it.

**Comment by hardikdevios** [comment]
+1 please add for Xcode

**Comment by zafarella** [comment]
@leewi9 @hardikdevios   how big `~/Library/Developer/Xcode/DerivedData` can be in average?

**Comment by hardikdevios** [comment]
It totally Depends on what kind of Project you are working on. My Derived Data is Generally belongs to **1 GB to 1.5 GB** but i used to clean up it regularly  because i have tons of external dependencies.

one more thing please change the Title of this thread to something more authentic one instead of "pls" to "Xcode derived data ramdisk" or something like that  just for proper index and easily find for other users.:)

**Comment by zafarella** [comment]
@leewi9  @hardikdevios  keen to hear some feedback. Tested with small iOS app on my machine - looks pretty good.

**Comment by hardikdevios** [comment]
I will update you shortly

**Comment by hardikdevios** [comment]
**Awesome Working!** 👍  Thanks Bro, Please update **ReadME.md** with Xcode in list of apps, i hope many more will join as they want most for Xcode so it would be great if you add there. Thanks once again.
